# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('solar_panels', models.FloatField(null=True)),
                ('power_of_panels', models.FloatField(null=True)),
                ('losses', models.FloatField(null=True)),
                ('battery', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=75)),
                ('password', models.CharField(max_length=80)),
            ],
        ),
    ]
