# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heliox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('power', models.FloatField(default=10)),
                ('category', models.CharField(choices=[('p', 'Personal'), ('e', 'Electronic'), ('h', 'House')], default='p', max_length=1)),
            ],
        ),
    ]
