# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 12:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heliox', '0002_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('duration', models.FloatField(default=15)),
                ('energy', models.FloatField(default=0.5)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heliox.Devices')),
            ],
        ),
    ]
